### ISSUE TITLE
Wrong video for Tempus talk

### ISSUE THREAD

**Issue by Rondom** [FOSDEM/videobox#22]
The [video](http://video.fosdem.org/2016/aw1121/tempus-a-framework-for-multimodal-trip-planning.mp4) for the talk [Tempus - a framework for multimodal trip planning](https://fosdem.org/2016/schedule/event/geo_tempus/) is not the right video. It shows the later talk [100% open journey planning](https://fosdem.org/2016/schedule/event/geo_openjourney/)

**Comment by Thulinma** [comment]
Thanks for letting us know - we'll get it sorted soonish.

**Comment by johanvdw** [comment]
Note that timings are correct (I believe) - it should need reencoding, actually both talks need reencoding: 4238 and 3774 .

**Comment by johanvdw** [comment]
Thanks for fixing! This issue can be closed.

**Comment by Thulinma** [comment]
Great. Didn't have time to checked the fixed file yet. Always handy when things get confirmed for you, thanks! :-)
