### ISSUE TITLE
broken video files of h2214 room

### ISSUE THREAD

**Issue by vlet** [FOSDEM/videobox#28]
Perl talks video files are broken and there are also keep growing in size, for now there are about 1G each (more than 10 times bigger than expected)

https://video.fosdem.org/2016/h2214/?C=M&O=D

**Comment by Thulinma** [comment]
The encodes for some reason never stopped. I just stopped them, and files should be playable once mirrors sync up. There's likely other issues with the files as well - we'll re-encode them soon-ish (some other rooms had similar issues - we'll probably do them all at once when most material is online).
Thanks for letting us know!

**Comment by Thulinma** [comment]
All fixed now.
