### ISSUE TITLE
Recently added videos are corrupted

### ISSUE THREAD

**Issue by yggdr** [FOSDEM/videobox#30]
Hi,

the recently added videos like whats new in perl, perl 6,  perl and mathematics, or the videos in k4601 seem to have a weird format that neither my mpv, nor firefox can play. Older videos seem to be still ok.
Firefox just tells me the file is corrupt, while mpv reports:

    $ mpv always-in-the-shadow-the-history-of-minix-vmd.mp4 
    Playing: always-in-the-shadow-the-history-of-minix-vmd.mp4
    [ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: moov atom not found
    [lavf] avformat_open_input() failed
    [ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: moov atom not found
    [lavf] avformat_open_input() failed
    Failed to recognize file format.
    
    Exiting... (Errors when loading file)

`file always-in-the-shadow-the-history-of-minix-vmd.mp4` reports:
`always-in-the-shadow-the-history-of-minix-vmd.mp4: ISO Media, MP4 Base Media v1 [IS0 14496-12:2003]`

edit
Somehow I managed to completely overlook this issue: https://github.com/FOSDEM/videobox/issues/28
Sorry for (partial) duplicating
/edit

**Comment by Thulinma** [comment]
Thanks for mentioning this - we don't have a full list of all affected videos yet.
We will seek them out and re-do them as needed, somewhere in the coming few weeks.

**Comment by Thulinma** [comment]
All corrupt files should now be working.
