### ISSUE TITLE
Where is Kicad EDA videos?

### ISSUE THREAD

**Issue by eldarkg** [FOSDEM/videobox#32]
[Link to](http://video.fosdem.org/2016/aw1121/). 
[STATUS.txt](http://video.fosdem.org/2016/aw1121/STATUS.TXT):
OK: 'Designing with KiCAD of OSHW 64-bit ARM board'
OK: 'KiCad Project Status'

**Comment by Thulinma** [comment]
Most likely an encoding error.

"OK" means the original recording has been checked by a human and is confirmed to be good, as well as the begin/end time were marked. Those markings are then fed into an encoding script that generates the files, but sometimes it encounters a problem and fails (a typo in the marking, for example).

Rest assured it will be available soon; we're just finishing up marking everything first before we go back and fix the errors that occurred.
Leaving this issue open as a reminder.

**Comment by eldarkg** [comment]
Thank you for response. I'll wait

**Comment by Thulinma** [comment]
Problem found - encodes should be available within the next 1-2 hours.

**Comment by eldarkg** [comment]
Thank you
