### ISSUE TITLE
Mis-named video in http://video.fosdem.org/2016/ud2120/

### ISSUE THREAD

**Issue by danielinux** [FOSDEM/videobox#33]
http://ftp.fau.de/fosdem/2016/ud2120/frosted-embedded-posix-os.mp4 is in fact the "Turris Omnia" talk.

Where is the frosted video? :)

**Comment by danielinux** [comment]
ping?

**Comment by Thulinma** [comment]
Taking a look at this soon! Most likely something was simply mistyped or mislabeled somewhere.

**Comment by danielinux** [comment]
Can we at least re-label the video with the correct title, so people looking for the frosted talk are not confused, and people looking for the Turris Omnia talk can find it?

**Comment by Thulinma** [comment]
Re-encodes are running now to fix both talks. Should both be online within the next hour or so.

**Comment by danielinux** [comment]
Thanks!
