### ISSUE TITLE
h2214 Perl Videos Issues

### ISSUE THREAD

**Issue by TBSliver** [FOSDEM/videobox#39]
Hi there, went through all the videos from the Perl dev room and have gone over each of the videos available and the issues which they are each exhibiting. I have noticed that one of the issues has already been picked up on in #28, however I have left my comments for this inside the list.

# Fosdem Perl Room Video Checkup

These are the errors for the Perl room - the videos I will be looking at are the following from [video.fosdem.org](http://video.fosdem.org/2016/h2214/). These are the listed items from the schedule:

* Welcome To The Perl Devroom
* The Pinnacle of Hubris
* Perl 6 - Why People Are So Excited
* Rperl, Perl11, and the Future of Perl Performance
* Perl and Mathematics
* PONAPI
* Crust
* From Regular Expressions to Parsing JavaScript
* Teaching Perl
* Assembly programming for Perl programmers
* Perl is not dead,... it got better!
* Whats new in Perl?
* Perl 6 - The end of the Beginning
* See you next year

However of these, the first and last ('Welcome to...' and 'See you next year') did not have any talk itself presented there, so should not have a video.

## Welcome To The Perl Devroom

[Video Link](http://ftp.fau.de/fosdem/2016/h2214/welcome-to-the-perl-devroom.mp4)

Note that this talk was only a few seconds at the beginning of the perl room, so really does not need a video. Here are the issues though:

* All from The Pinnacle of Hubris
* No video for first 57 seconds
* Video and speaker audio out of sync
* Cant tell if speaker and slides are in or out of sync.

## The Pinnacle of Hubris

Video not available.

## Perl 6 - Why People Are so Excited

Video not available.

## Rperl, Perl11, and the Future of Perl Performance

[Video Link](http://mirror.onet.pl/pub/mirrors/video.fosdem.org/2016/h2214/rperl-perl-11-and-the-future-of-perl-performance.mp4)

* missed the beginning of the talk
* Speaker audio and video out of sync (by about 15 seconds or so)
* No slides at all
* Video is 43 HOURS long

## Perl and Mathematics

[Video Link](http://video.fosdem.org/2016/h2214/perl-and-mathematics.mp4)

* Missed the beginning of the talk
* Video is 43 HOURS long
* speaker audio and video is out of sync by about a second or 2
* No slides

## PONAPI

[Video Link](http://video.fosdem.org/2016/h2214/ponapi.mp4)

* Missed the beginning of the talk1
* Speaker and video is out of sync
* No slides
* Video is 43 HOURS long

## Crust

[Video Link](http://mirror.onet.pl/pub/mirrors/video.fosdem.org/2016/h2214/crust.mp4)

* Missing the beginning of the talk
* speaker and video is out of sync
* No slides
* Video is 43 HOURS long

## From Regular Expressions to Parsing JavaScript

[Video Link](http://ftp.fau.de/fosdem/2016/h2214/from-regular-expressions-to-parsing-javascript.mp4)

* Missing the beggining of the talk
* speaker and audio is out of sync
* No slides
* Video is 43HOURS long

## Teaching Perl

[Video Link](http://mirror.as35701.net/video.fosdem.org/2016/h2214/teaching-perl.mp4)

* Beginning of the talk is missing
* speaker and audio is out of sync
* no slides
* Video is 43 hours long....

## Assembly programming for Perl programmers

[Video Link](http://bofh.nikhef.nl/events/FOSDEM/2016/h2214/amd64-assembly-programming-for-perl-programmers.mp4)

* Beginning of the talk is missing
* speaker and audio is out of sync
* no slides
* Video is 43 hours long....

## Perl is not dead,... it got better!

[Video Link](http://mirrors.dotsrc.org/fosdem/2016/h2214/perl-is-not-dead-it-got-better.mp4)

* Beginning of the talk is missing
* speaker and audio is out of sync
* no slides
* Video is 43 hours long....

## Whats new in Perl?

[Video Link](http://mirrors.dotsrc.org/fosdem/2016/h2214/whats-new-in-perl.mp4)

* Beginning of the talk is missing
* speaker and audio is out of sync
* no slides
* Video is 43 hours long....

## Perl 6 - The end of the Beginning

Video not available.

## See you next year

This does not exist as a video, which is correct.

**Comment by TBSliver** [comment]
Below are all the workings out for the videos for all of the videos. the biggest thing to note was that the original video file specified for the slides was completely wrong -   it was specified as `16-01-31_083441.ts` and should have been `16-01-31_083019.ts`, with all the timestamps modified accordingly. All video has been timed using VLC media player, and has been done from the speakers file `16-01-31_083339.ts` - including working out the slides video times. Hopefully the timestamps on the files are accurate, otherwise this will cause issues in the slide video segments.

# TBSliver's Notes

Difference between start of speaker (08:33:39) and start of slide (08:30:19)
main videos: 3:20 (200)

# 4593.txt - Welcome To The Perl Devroom

## Speaker

* Start: 26:20 = 1580
* End: 27:08 = 1628
* Total: 48 seconds

## Slides

No Slides

# 4594.txt - The Pinnacle of Hubris

## Speaker

* Start: 27:08 = 1628
* End: 1:07:25 = 4045
* Total: 2417 seconds

## Slides

* Start: 1628 + 200 = 1828
* End: 4045 + 200 = 4245

# 4595.txt - Perl 6 - Why People Are So Excited

## Speaker

* Start: 1:16:31 = 4591
* End: 1:58:39 = 7119
* Total: 2528 seconds

## Slides

* Start: 4591 + 200 = 4791
* End: 7119 + 200 = 7319

# 4596.txt - Rperl, Perl11, and the Future of Perl Performance

## Speaker

* Start: 2:02:57 = 7377
* End: 2:41:50 = 9710
* Total: 2333 seconds

## Slides

* Start: 7377 + 200 = 7577
* End: 9710 + 200 = 9910

# 4597.txt - Perl and Mathematics

## Speaker

* Start: 2:45:51 = 9951
* End: 3:22:12 = 12132
* Total: 2181 seconds

## Slides

* Start: 9951 + 200 = 10151
* End: 12132 + 200 = 12332

# 4598.txt - PONAPI

## Speaker

* Start: 3:30:13 = 12613
* End: 3:49:53 = 13793
* Total: 1180 seconds

## Slides

* Start: 12613 + 200 = 12813
* End: 13793 + 200 = 13993

# 4599.txt - Crust

## Speaker

* Start: 4:05:20 = 14720
* End: 4:35:56 = 16556
* Total: 1836 seconds

## Slides

* Start: 14720 + 200 = 14920
* End: 16556 + 200 = 16756

# 4600.txt - From Regular Expressions to Parsing JavaScript

## Speaker

* Start: 4:52:23 = 17543
* End: 5:31:43 = 19903
* Total: 2360 seconds

## Slides

* Start: 17543 + 200 = 17743
* End: 19903 + 200 = 20103

# 4601.txt - Teaching Perl

## Speaker

* Start: 5:36:00 = 20160
* End: 5:57:08 = 21428
* Total: 1268 seconds

## Slides

* Start: 20160 + 200 = 20360
* End: 21428 + 200 = 21628

# 4602.txt - Assembly programming for Perl programmers

## Speaker

* Start: 6:00:56 = 21656
* End: 6:23:03 = 22983
* Total: 1327 seconds

## Slides

* Start: 21656 + 200 = 21856
* End: 22983 + 200 = 23183

# 4603.txt - Perl is not dead,... it got better!

## Speaker

* Start: 6:26:27 = 23187
* End: 6:45:56 = 24356
* Total: 1169 seconds

## Slides

* Start: 23187 + 200 = 23387
* End: 24356 + 200 = 24556

# 4604.txt - Whats new in Perl?

## Speaker

* Start: 6:49:48 = 24588
* End: 7:27:34 = 26854
* Total: 2266 seconds

## Slides

* Start: 24588 + 200 = 24788
* End: 26854 + 200 = 27054

# 4605.txt - Perl 6 - The end of the Beginning

## Speaker

* Start: 7:33:10 = 27190
* End: 8:21:34 = 30094
* Total: 2904 seconds

Mic audio dies at 8:02:52

## Slides

* Start: 27190 + 200 = 27390
* End: 30094 + 200 = 30294

# 4607.txt - See you next year

Lost

**Comment by TBSliver** [comment]
Note that all the commits are in PR #40

**Comment by Thulinma** [comment]
Should be corrected after the re-encode finishes. Feel free to re-open if anything still doesn't look right in a few hours from now.
