### ISSUE TITLE
Size of the talk "Make your own USB device without pain and money"  is 0 bytes

### ISSUE THREAD

**Issue by AndreySV** [FOSDEM/videobox#41]
Talk:
"Make your own USB device without pain and money!"
Turn your Linux board into a custom USB device.

Link for the quick look of 0 size problem:
https://video.fosdem.org/2016/ud2120/

Direct link to the empty file:
https://video.fosdem.org/2016/ud2120/make-your-own-usb-device-without-pain-and-money.mp4

**Comment by Thulinma** [comment]
Thanks for pointing this out. Fixed in 050e14b2e2de4c5a18888590ab314e46d06e24a8
Re-encode is running now, should be up within the next hour.
