### ISSUE TITLE
Unable to rsync from mirrors.dotsrc.org

### ISSUE THREAD

**Issue by AndersTrier** [FOSDEM/videobox#44]
Hi
Since around 2016/09/19 we have been unable to rsync with rsync.fosdem.org from mirrors.dotsrc.org
```
$ host mirrors.dotsrc.org
mirrors.dotsrc.org has address 130.225.254.116
mirrors.dotsrc.org has IPv6 address 2001:878:346::116
```
rsync fails with:
```
@ERROR: access denied to video from kvaser.dotsrc.org (130.225.254.116)
rsync error: error starting client-server protocol (code 5) at main.c(1653) [Receiver=3.1.1]
Exit status: 5
```

**Comment by AndersTrier** [comment]
Works again.

**Comment by AndersTrier** [comment]
Well, it worked for a few days. Starting on 2016-09-29 I'm getting the same error.

**Comment by gerryd** [comment]
Hi Anders,

Thanks for reporting this issue. It seems you are now syncing from a new IP address which was not whitelisted. I have added it to the whitelist, you should be able to sync again.

Feel free to reopen if it still isn't resolved!
